---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>

platforms:
  - name: ubuntu-16.04
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[webserver_test::default]
    attributes:
